name: Tests

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Run tests

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Set Poetry environment
        run: |
          poetry env use 3.11

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run
        run: |
          poetry run xxx
